// Code generated by ent, DO NOT EDIT.

package member

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/boykush/famoney/server/family/internal/infra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldID, id))
}

// OidcSubject applies equality check predicate on the "oidc_subject" field. It's identical to OidcSubjectEQ.
func OidcSubject(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldOidcSubject, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldDisplayName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCreatedAt, v))
}

// OidcSubjectEQ applies the EQ predicate on the "oidc_subject" field.
func OidcSubjectEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldOidcSubject, v))
}

// OidcSubjectNEQ applies the NEQ predicate on the "oidc_subject" field.
func OidcSubjectNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldOidcSubject, v))
}

// OidcSubjectIn applies the In predicate on the "oidc_subject" field.
func OidcSubjectIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldOidcSubject, vs...))
}

// OidcSubjectNotIn applies the NotIn predicate on the "oidc_subject" field.
func OidcSubjectNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldOidcSubject, vs...))
}

// OidcSubjectGT applies the GT predicate on the "oidc_subject" field.
func OidcSubjectGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldOidcSubject, v))
}

// OidcSubjectGTE applies the GTE predicate on the "oidc_subject" field.
func OidcSubjectGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldOidcSubject, v))
}

// OidcSubjectLT applies the LT predicate on the "oidc_subject" field.
func OidcSubjectLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldOidcSubject, v))
}

// OidcSubjectLTE applies the LTE predicate on the "oidc_subject" field.
func OidcSubjectLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldOidcSubject, v))
}

// OidcSubjectContains applies the Contains predicate on the "oidc_subject" field.
func OidcSubjectContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldOidcSubject, v))
}

// OidcSubjectHasPrefix applies the HasPrefix predicate on the "oidc_subject" field.
func OidcSubjectHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldOidcSubject, v))
}

// OidcSubjectHasSuffix applies the HasSuffix predicate on the "oidc_subject" field.
func OidcSubjectHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldOidcSubject, v))
}

// OidcSubjectEqualFold applies the EqualFold predicate on the "oidc_subject" field.
func OidcSubjectEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldOidcSubject, v))
}

// OidcSubjectContainsFold applies the ContainsFold predicate on the "oidc_subject" field.
func OidcSubjectContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldOidcSubject, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldDisplayName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Member) predicate.Member {
	return predicate.Member(sql.NotPredicates(p))
}
