// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/boykush/famoney/server/family/internal/infra/ent/member"
	"github.com/boykush/famoney/server/family/internal/infra/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescOidcSubject is the schema descriptor for oidc_subject field.
	memberDescOidcSubject := memberFields[0].Descriptor()
	// member.OidcSubjectValidator is a validator for the "oidc_subject" field. It is called by the builders before save.
	member.OidcSubjectValidator = memberDescOidcSubject.Validators[0].(func(string) error)
	// memberDescDisplayName is the schema descriptor for display_name field.
	memberDescDisplayName := memberFields[1].Descriptor()
	// member.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	member.DisplayNameValidator = memberDescDisplayName.Validators[0].(func(string) error)
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberFields[2].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
}
