#!/usr/bin/env bash
#MISE description="Create new migration for expense"
#MISE dir="server/expense"

if [ -z "$1" ]; then
  echo "Usage: mise run db:migrate:diff:expense <migration_name>"
  exit 1
fi

atlas migrate diff "$1" --env local
