#!/usr/bin/env bash
#MISE description="Create new migration for family"
#MISE dir="server/family"

if [ -z "$1" ]; then
  echo "Usage: mise run db:migrate:diff:family <migration_name>"
  exit 1
fi

atlas migrate diff "$1" --env local
