-- Create "members" table
CREATE TABLE "members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "oidc_subject" character varying NOT NULL,
  "display_name" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "members_oidc_subject_key" to table: "members"
CREATE UNIQUE INDEX "members_oidc_subject_key" ON "members" ("oidc_subject");
