apiVersion: batch/v1
kind: Job
metadata:
  name: expense-migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: migrate
        image: expense-migration:latest
        env:
        - name: DATABASE_URL
          value: postgres://famoney:famoney-local-password@postgres-rw:5432/expense_db?sslmode=disable
      restartPolicy: Never
  backoffLimit: 3
