name: Server Test CI

on:
  pull_request:
    paths:
      - 'server/**'
      - '.mise-tasks/server/test'
      - '.github/workflows/server-test-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.mise-tasks/server/test'
      - '.github/workflows/server-test-ci.yml'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - name: Run server API tests
        run: mise run server:test
