apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: expense_db
      owner: famoney
      postInitSQL:
      - CREATE DATABASE family_db OWNER famoney
      - CREATE DATABASE keycloak_db OWNER famoney
  managed:
    roles:
    - name: famoney
      login: true
      passwordSecret:
        name: postgres-user-secret
