apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/basic-auth
stringData:
  username: famoney
  password: famoney-local-password
